#include <stdio.h>
#include <fftw3.h>
#include "nativefft_NativeFFT.h"   // this header file was generated by javah
JNIEXPORT void JNICALL Java_nativefft_NativeFFT_displayMessage(JNIEnv *env, jobject obj)
{
  printf("Hello World!\n");
}

static int blocksize = 0;
static fftw_plan p;
static fftw_complex *in, *out;

JNIEXPORT void JNICALL Java_nativefft_NativeFFT_initFFT(JNIEnv *env, jobject obj, jint bs)
{
  printf("Init: bs=%d\n", bs);
  blocksize = bs;
  
         
  in = (fftw_complex*) fftw_malloc(sizeof(fftw_complex) * blocksize);
  out = (fftw_complex*) fftw_malloc(sizeof(fftw_complex) * blocksize);
  p = fftw_plan_dft_1d(blocksize, in, out, FFTW_FORWARD, FFTW_ESTIMATE);
         
  //fftw_destroy_plan(p);
  //fftw_free(in); fftw_free(out);
}

JNIEXPORT jint JNICALL Java_nativefft_NativeFFT_doFFT(JNIEnv *env, jobject obj, jdoubleArray data_in, jdoubleArray data_out)
{
    jdouble *c_in, *c_out;
    c_in = (*env)->GetDoubleArrayElements(env, data_in, NULL);
    for(int i = 0; i < blocksize; i++){
        in[i][0] = c_in[i];
        in[i][1] = 0;
    }
    (*env)->ReleaseDoubleArrayElements(env, data_in, c_in, 0);
    
    fftw_execute(p);
    
    c_out = (*env)->GetDoubleArrayElements(env, data_out, NULL);
    for(int i = 0; i < blocksize/2; i++){
        c_out[i*2] = out[i][0];
        c_out[(i*2)+1] = out[i][1];
    }
    (*env)->ReleaseDoubleArrayElements(env, data_out, c_out, 0);
    return 42;
}
  