/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativefft_NativeFFT */

#ifndef _Included_nativefft_NativeFFT
#define _Included_nativefft_NativeFFT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativefft_NativeFFT
 * Method:    displayMessage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativefft_NativeFFT_displayMessage
  (JNIEnv *, jobject);

/*
 * Class:     nativefft_NativeFFT
 * Method:    initFFT
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nativefft_NativeFFT_initFFT
  (JNIEnv *, jobject, jint);

/*
 * Class:     nativefft_NativeFFT
 * Method:    doFFT
 * Signature: ([D[D)I
 */
JNIEXPORT jint JNICALL Java_nativefft_NativeFFT_doFFT
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
